/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    // Basic background colors
    'bg-gray-500',
    'bg-blue-500',
    'bg-red-500',
    'bg-green-500',
    'bg-yellow-500',
    'bg-orange-500',
    'bg-amber-500',
    'bg-white',
    'bg-black',
    
    // Text colors
    'text-white',
    'text-black',
    'text-gray-500',
    'text-blue-500',
    'text-red-500',
    'text-green-500',
    'text-yellow-500',
    'text-orange-500',
    'text-amber-500',
    
    // Gradients
    'bg-gradient-to-r',
    'bg-gradient-to-br',
    'from-yellow-400',
    'via-amber-400',
    'to-orange-400',
    'from-yellow-500',
    'to-orange-500',
    'from-yellow-600',
    'via-amber-600',
    'to-orange-600',
    'text-transparent',
    'bg-clip-text',
    'drop-shadow-lg',
    'animate-pulse',
    'animate-bounce',
    'hover:scale-110',
    'transform',
    'transition-transform',
    'duration-300',
    'opacity-10',
    'rounded-3xl',
    'rounded-2xl',
    'rounded-xl',
    'shadow-2xl',
    'shadow-lg',
    'border-2',
    'border-yellow-200',
    'border-yellow-300',
    'text-yellow-600',
    'text-gray-700',
    'text-gray-800',
    'font-bold',
    'font-light',
    'text-6xl',
    'text-7xl',
    'text-2xl',
    'text-3xl',
    'md:text-3xl',
    'md:text-4xl',
    'md:text-7xl',
    'tracking-wide',
    'mb-6',
    'mb-4',
    'mt-4',
    'py-12',
    'px-4',
    'gap-6',
    'gap-4',
    'justify-center',
    'items-center',
    'flex',
    'relative',
    'absolute',
    'inset-0',
    'z-10',
    'w-24',
    'h-1',
    'rounded-full'
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}