import type { BeeCharacter } from './types';

const BEE_COLORS = ['#42A5F5', '#66BB6A', '#AB47BC', '#FFA726', '#EF5350'];

export const BEE_CHARACTERS: BeeCharacter[] = [
  {
    name: "Bumble Bill",
    description: "A friendly, fuzzy bee who loves to leisurely explore gardens.",
    color: BEE_COLORS[0],
    flipped: false,
  },
  {
    name: "Zippy",
    description: "A speedy scout, always the first to find the freshest flowers.",
    color: BEE_COLORS[1],
    flipped: false,
  },
  {
    name: "Nectar Nebula",
    description: "A dreamy bee who sees the cosmos in every drop of nectar.",
    color: BEE_COLORS[2],
    flipped: false,
  },
  {
    name: "Queen Bee-yoncé",
    description: "The fierce and fabulous leader of her hive, always on point.",
    color: BEE_COLORS[3],
    flipped: false,
  },
  {
    name: "Pollen Penny",
    description: "A diligent worker, known for her impressive pollen-gathering skills.",
    color: BEE_COLORS[4],
    flipped: false,
  },
  {
    name: "Barnaby Buzz",
    description: "A cheerful bee who hums happy tunes while he works.",
    color: BEE_COLORS[0],
    flipped: true,
  },
  {
    name: "Poppy Pollen",
    description: "An artistic bee who loves the vibrant colors of wildflowers.",
    color: BEE_COLORS[1],
    flipped: true,
  },
  {
    name: "Waggle Wanda",
    description: "A social bee who loves telling others where the best flowers are.",
    color: BEE_COLORS[2],
    flipped: true,
  },
  {
    name: "Fuzzy Frank",
    description: "A gentle giant, known for his extra-fluffy coat.",
    color: BEE_COLORS[3],
    flipped: true,
  },
  {
    name: "Clover Cassie",
    description: "An explorer who knows where to find the sweetest clover patches.",
    color: BEE_COLORS[4],
    flipped: true,
  },
];

export const BEE_FACTS: string[] = [
  "Honeybees beat their wings 200 times per second, creating their signature buzz.",
  "A single bee produces only about 1/12th of a teaspoon of honey in its lifetime.",
  "Bees have five eyes: two large compound eyes and three smaller ocelli eyes in the center of their head.",
  "To make one pound of honey, a bee colony must visit about 2 million flowers.",
  "Bees communicate through a special 'waggle dance' to tell others where to find good sources of nectar.",
  "Queen bees can live for up to five years and lay up to 2,500 eggs a day during peak season.",
  "Bumblebees can flap their wings even when detached from their flight muscles, which helps them warm up in cold weather.",
  "Bees are responsible for pollinating about one-third of the food we eat.",
  "The average honeybee can fly at a speed of about 15 miles per hour.",
  "Bees have been producing honey from flowering plants for 10-20 million years.",
  "Male bees, called drones, do not have stingers. Their only purpose is to mate with the queen.",
  "A bee's brain is about the size of a sesame seed, but it's incredibly efficient at learning and remembering.",
  "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still edible.",
  "Bees can recognize individual human faces.",
  "Bumblebees have 'smelly feet' that leave a scent on flowers they've visited, letting other bees know the nectar is gone.",
  "Some bees, like mason bees, are solitary and don't live in hives. They make their nests in hollow reeds or holes in wood.",
  "The study of honey bees is called 'apiculture'.",
  "Bees are found on every continent on Earth except for Antarctica.",
  "A single bee colony can contain between 20,000 and 60,000 bees.",
  "Bees use the sun as a compass, but they can also navigate on cloudy days by using polarized light.",
  "The 'bee's knees' was a popular 1920s slang term meaning 'the best'.",
  "Not all bees are yellow and black. The Blue Orchard Mason Bee, for example, is a metallic dark blue.",
  "When a honeybee stings, its stinger gets lodged in the skin, and the bee dies shortly after.",
  "Bees are technically a type of wasp that evolved to be vegetarian.",
  "A queen bee is at her busiest in the summer months, when the hive needs to be at its maximum strength.",
  "Worker bees are all female and perform all the tasks in the hive, from cleaning to foraging.",
  "Bees have two pairs of wings that hook together when they fly and unhook when they are not flying.",
  "Over 4,000 species of bees are native to the United States.",
  "The temperature inside a honeybee hive is kept at a constant 93°F (34°C) year-round.",
  "Bees' wings stroke in a figure-8 pattern.",
  "The color of honey depends on the nectar source visited by the honey bees.",
  "The ancient Greeks and Romans saw the bee as a symbol of diligence, wealth, and eloquence.",
  "A bee's sense of smell is so precise that it can differentiate between hundreds of different floral varieties from miles away.",
  "During winter, honey bees cluster together in a 'winter cluster' to keep the queen and themselves warm.",
  "Only female bees can sting. Male drones are defenseless.",
  "The world's largest bee, Wallace's giant bee, is about the size of a human thumb.",
  "Some species of 'cuckoo bees' lay their eggs in the nests of other bee species, similar to cuckoo birds.",
  "Honey contains natural preservatives that prevent it from spoiling, which is why it can last for thousands of years.",
  "Bees' hairs are electrostatically charged, which helps pollen grains stick to their bodies.",
  "A bee must fly about 55,000 miles to produce one pound of honey."
];

export const FLOWER_DATA: { [key: string]: string[] } = {
  "AL": ["Camelia", "Oak-leaf Hydrangea", "Trumpet Creeper", "Azalea"],
  "AK": ["Forget-me-not", "Fireweed", "Wild Iris", "Labrador Tea"],
  "AZ": ["Saguaro Cactus Blossom", "Desert Marigold", "Prickly Pear Cactus", "Brittlebush"],
  "AR": ["Apple Blossom", "Winecup", "Butterfly Milkweed", "Purple Coneflower"],
  "CA": ["California Poppy", "Lupine", "Ceanothus", "Salvia"],
  "CO": ["Rocky Mountain Columbine", "Blanket Flower", "Penstemon", "Blue Flax"],
  "CT": ["Mountain Laurel", "New England Aster", "Joe-Pye Weed", "Swamp Milkweed"],
  "DE": ["Peach Blossom", "Sweet Pepperbush", "Butterfly Weed", "Seaside Goldenrod"],
  "FL": ["Orange Blossom", "Tickseed", "Saw Palmetto", "Spanish Needle"],
  "GA": ["Cherokee Rose", "Black-eyed Susan", "Azalea", "Trumpet Creeper"],
  "HI": ["Hibiscus", "ʻŌhiʻa lehua", "Naupaka", "ʻIlima"],
  "ID": ["Syringa", "Arrowleaf Balsamroot", "Penstemon", "Blanket Flower"],
  "IL": ["Violet", "Purple Coneflower", "Prairie Blazing Star", "Common Milkweed"],
  "IN": ["Peony", "Butterfly Weed", "Wild Bergamot", "Purple Coneflower"],
  "IA": ["Wild Rose", "Gray-headed Coneflower", "Purple Prairie Clover", "Compass Plant"],
  "KS": ["Sunflower", "Plains Coreopsis", "Purple Poppy Mallow", "Blue Sage"],
  "KY": ["Goldenrod", "Trumpet Vine", "Blazing Star", "Purple Coneflower"],
  "LA": ["Magnolia", "Louisiana Iris", "Black-eyed Susan", "Buttonbush"],
  "ME": ["Lupine", "Wild Blueberry", "Goldenrod", "New England Aster"],
  "MD": ["Black-eyed Susan", "Joe-Pye Weed", "Swamp Milkweed", "Goldenrod"],
  "MA": ["Mayflower", "New England Aster", "Goldenrod", "Wild Bergamot"],
  "MI": ["Apple Blossom", "Michigan Lily", "Joe-Pye Weed", "Common Milkweed"],
  "MN": ["Pink and White Lady's Slipper", "Blazing Star", "Purple Prairie Clover", "Wild Bergamot"],
  "MS": ["Magnolia", "Swamp Mallow", "Black-eyed Susan", "Trumpet Creeper"],
  "MO": ["Hawthorn", "Pale Purple Coneflower", "Glade Coneflower", "Wild Bergamot"],
  "MT": ["Bitterroot", "Indian Paintbrush", "Silvery Lupine", "Blanket Flower"],
  "NE": ["Goldenrod", "Shell-leaf Penstemon", "Purple Prairie Clover", "Butterfly Milkweed"],
  "NV": ["Sagebrush", "Desert Globemallow", "Desert Paintbrush", "Apricot Mallow"],
  "NH": ["Purple Lilac", "Wild Bergamot", "New England Aster", "Goldenrod"],
  "NJ": ["Violet", "Swamp Milkweed", "Joe-Pye Weed", "New York Ironweed"],
  "NM": ["Yucca Flower", "Chocolate Flower", "Desert Willow", "Blanket Flower"],
  "NY": ["Rose", "Bee Balm", "Goldenrod", "New England Aster"],
  "NC": ["Dogwood", "Cardinal Flower", "Carolina Jessamine", "Rhododendron"],
  "ND": ["Wild Prairie Rose", "Dotted Blazing Star", "Purple Prairie Clover", "Stiff Sunflower"],
  "OH": ["Scarlet Carnation", "Ohio Spiderwort", "Wild Bergamot", "Purple Coneflower"],
  "OK": ["Rose", "Indian Blanket", "Purple Prairie Clover", "Showy Milkweed", "Purple Poppy Mallow"],
  "OR": ["Oregon Grape", "Douglas Iris", "California Poppy", "Red-flowering Currant"],
  "PA": ["Mountain Laurel", "Wild Geranium", "Bee Balm", "Goldenrod"],
  "RI": ["Violet", "Marsh Marigold", "Swamp Milkweed", "Joe-Pye Weed"],
  "SC": ["Yellow Jessamine", "Goldenrod", "Trumpet Creeper", "Swamp Sunflower"],
  "SD": ["Pasque Flower", "Prairie Smoke", "Purple Coneflower", "Stiff Sunflower"],
  "TN": ["Iris", "Purple Passionflower", "Tennessee Coneflower", "Blazing Star"],
  "TX": ["Bluebonnet", "Texas Lantana", "Indian Paintbrush", "Black-eyed Susan"],
  "UT": ["Sego Lily", "Wasatch Penstemon", "Rocky Mountain Beeplant", "Arrowleaf Balsamroot"],
  "VT": ["Red Clover", "Foxglove Beardtongue", "New England Aster", "Joe-Pye Weed"],
  "VA": ["Dogwood", "Virginia Bluebell", "Butterfly Weed", "Mountain Mint"],
  "WA": ["Coast Rhododendron", "Pacific Bleeding Heart", "Salal", "Red Flowering Currant"],
  "WV": ["Rhododendron", "Flame Azalea", "Joe-Pye Weed", "Wild Bergamot"],
  "WI": ["Wood Violet", "Prairie Phlox", "Common Milkweed", "Blazing Star"],
  "WY": ["Indian Paintbrush", "Wyoming Townsend Daisy", "Rocky Mountain Beeplant", "Silky Lupine"],
  "default": ["Clover", "Dandelion", "Sunflower", "Lavender"]
};

export const US_STATES: { name: string; abbreviation: string }[] = [
    { name: 'Alabama', abbreviation: 'AL' },
    { name: 'Alaska', abbreviation: 'AK' },
    { name: 'Arizona', abbreviation: 'AZ' },
    { name: 'Arkansas', abbreviation: 'AR' },
    { name: 'California', abbreviation: 'CA' },
    { name: 'Colorado', abbreviation: 'CO' },
    { name: 'Connecticut', abbreviation: 'CT' },
    { name: 'Delaware', abbreviation: 'DE' },
    { name: 'Florida', abbreviation: 'FL' },
    { name: 'Georgia', abbreviation: 'GA' },
    { name: 'Hawaii', abbreviation: 'HI' },
    { name: 'Idaho', abbreviation: 'ID' },
    { name: 'Illinois', abbreviation: 'IL' },
    { name: 'Indiana', abbreviation: 'IN' },
    { name: 'Iowa', abbreviation: 'IA' },
    { name: 'Kansas', abbreviation: 'KS' },
    { name: 'Kentucky', abbreviation: 'KY' },
    { name: 'Louisiana', abbreviation: 'LA' },
    { name: 'Maine', abbreviation: 'ME' },
    { name: 'Maryland', abbreviation: 'MD' },
    { name: 'Massachusetts', abbreviation: 'MA' },
    { name: 'Michigan', abbreviation: 'MI' },
    { name: 'Minnesota', abbreviation: 'MN' },
    { name: 'Mississippi', abbreviation: 'MS' },
    { name: 'Missouri', abbreviation: 'MO' },
    { name: 'Montana', abbreviation: 'MT' },
    { name: 'Nebraska', abbreviation: 'NE' },
    { name: 'Nevada', abbreviation: 'NV' },
    { name: 'New Hampshire', abbreviation: 'NH' },
    { name: 'New Jersey', abbreviation: 'NJ' },
    { name: 'New Mexico', abbreviation: 'NM' },
    { name: 'New York', abbreviation: 'NY' },
    { name: 'North Carolina', abbreviation: 'NC' },
    { name: 'North Dakota', abbreviation: 'ND' },
    { name: 'Ohio', abbreviation: 'OH' },
    { name: 'Oklahoma', abbreviation: 'OK' },
    { name: 'Oregon', abbreviation: 'OR' },
    { name: 'Pennsylvania', abbreviation: 'PA' },
    { name: 'Rhode Island', abbreviation: 'RI' },
    { name: 'South Carolina', abbreviation: 'SC' },
    { name: 'South Dakota', abbreviation: 'SD' },
    { name: 'Tennessee', abbreviation: 'TN' },
    { name: 'Texas', abbreviation: 'TX' },
    { name: 'Utah', abbreviation: 'UT' },
    { name: 'Vermont', abbreviation: 'VT' },
    { name: 'Virginia', abbreviation: 'VA' },
    { name: 'Washington', abbreviation: 'WA' },
    { name: 'West Virginia', abbreviation: 'WV' },
    { name: 'Wisconsin', abbreviation: 'WI' },
    { name: 'Wyoming', abbreviation: 'WY' },
];